name: GitHub Actions Build and Push Docker Image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: euclid1990/rdbcbackup:latest
